services:
  db:
    image: mariadb:11.4
    container_name: cuisineLab_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - cuisineLab_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 180s

  wordpress:
    image: wordpress:6.8.3-php8.2-apache
    container_name: cuisineLab_wordpress
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8091:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - cuisineLab_wp_data:/var/www/html

  wpcli:
    image: wordpress:cli-php8.2
    container_name: cuisineLab_wpcli
    depends_on:
      db:
        condition: service_healthy
      wordpress:
        condition: service_started
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - cuisineLab_wp_data:/var/www/html
    profiles:
      - tools

volumes:
  cuisineLab_db_data:
  cuisineLab_wp_data:
